/**
 *
 * Sean
 * 2016-11-10
 *
 * https://leetcode.com/problems/find-the-difference/
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */
#include <iostream>
#include <string>
using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        int counts[26] = {0};
        for (auto c : t)
            ++counts[c-'a'];
        for (auto c : s)
            --counts[c-'a'];

        int i=0;
        for (; i<26; ++i) {
            if (counts[i])
                break;
        }
        return 'a'+i;
    }
};

int main() { return 0; }
